#
# Module manifest for module 'M365cde.GraphMail'
#
# Generated by: Dominik Gilgen
#
# Generated on: 2024-05-18
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'M365cde.GraphMail.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
 CompatiblePSEditions = @( 'Desktop', 'Core' )

# ID used to uniquely identify this module
GUID = '88df9600-1c64-4345-b85d-dcdf98655d2f'

# Author of this module
Author = 'Dominik Gilgen'

# Company or vendor of this module
CompanyName = 'Dominik Gilgen (Personal)'

# Copyright statement for this module
Copyright = '(c) 2024 Dominik Gilgen. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This function can be used for sending e-mails over Microsoft Graph. It is using the Microsoft.Graph module with the cmdlet Send-MgUserMail to send e-mails over Microsoft Exchange Online. It could be used within a script or a Azure Automation Runbook. There are multiple parameters available to customize the mail. The sender, recipient, CC, BCC, subject, content, attachment, importance, and reply to address can be customized.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Send-M365cdeMail')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Required Modules to run this module
RequiredModules   = @(
                          @{
                            ModuleName = "Microsoft.Graph.Authentication";
                            ModuleVersion = "2.15.0";
                            Guid = "883916f2-9184-46ee-b1f8-b6a2fb784cee"
                           },
                            @{
                             ModuleName = "Microsoft.Graph.Users.Actions";
                             ModuleVersion = "2.15.0";
                             Guid = "86213a25-bec4-4d70-8793-58670c62686f"
                            }
                         )


# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('PowerShell', 'Module', 'Automation')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/M365-Consultant/GraphMail/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/M365-Consultant/GraphMail'

        # ReleaseNotes of this module
        ReleaseNotes = @'
v1.0.0 - 2024-05-21
First final release of the module.

v0.0.1 - 2024-05-21
Initial release of the module.
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

}